# Generated by Django 5.2 on 2025-08-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student_info",
            fields=[
                ("student_name", models.CharField(max_length=100)),
                (
                    "std_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("bod", models.DateField(default="2000-01-01")),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default=True,
                        max_length=7,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("contact", models.IntegerField()),
                ("student_class", models.CharField(default=True, max_length=10)),
            ],
        ),
    ]
