# Generated by Django 5.2 on 2025-08-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_student_attendence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student_attendence",
            old_name="Student_id",
            new_name="Student",
        ),
    ]
