# Generated by Django 5.2 on 2025-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_student_attendence_std_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="student_attendence",
            constraint=models.UniqueConstraint(
                fields=("std_id", "A_date"), name="uniqe_data_with_std_id"
            ),
        ),
    ]
