# Generated by Django 5.2 on 2025-08-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_student_id_student_attendence_student"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student_attendence",
            name="unique_attendance_per_day",
        ),
        migrations.AddConstraint(
            model_name="student_attendence",
            constraint=models.UniqueConstraint(
                fields=("Student", "date"), name="unique_attendance_per_day"
            ),
        ),
    ]
