# Generated by Django 5.2 on 2025-08-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_student_attendence_uniqe_data_with_std_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student_attendence",
            name="uniqe_data_with_std_id",
        ),
        migrations.RenameField(
            model_name="student_attendence",
            old_name="attendence",
            new_name="attendance",
        ),
        migrations.RenameField(
            model_name="student_attendence",
            old_name="A_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="student_attendence",
            name="std_id",
        ),
        migrations.RemoveField(
            model_name="student_attendence",
            name="student_name",
        ),
        migrations.AddField(
            model_name="student_attendence",
            name="student",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.student_info",
            ),
        ),
        migrations.AddConstraint(
            model_name="student_attendence",
            constraint=models.UniqueConstraint(
                fields=("student", "date"), name="unique_attendance_per_day"
            ),
        ),
    ]
