# Generated by Django 6.0.5 on 2026-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ams_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("teacher", "Teacher"),
                    ("perents", "Perents"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
